locale: "en-CN"
title: Serendipity-zsh # Title of your site
url: "https://serendipity-zsh.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description:  > # this means to ignore newlines until "baseurl:"
  不断学习，不断进步

# Author details for the jekyll-seo-tag gem
author: 
  name: Serendipity-zsh
  email: 1141792212@qq.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: my github
  links:
    - https://github.com/Serendipity-zsh

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
