# Basic
title: Serendipity-zsh
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: Serendipity-zsh
# 头像里面的描述
avatarDesc: Java / 后台开发
url: "Serendipity-zsh.github.io"

# Comment
comment:
    disqus: Serendipity_zsh
    # gitment: Serendipity-zsh    # 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 友言id,登录友言官网申请

# Social
social:
    #weibo:  
    github: Serendipity-zsh
    zhihu: hai-hao-52-25/activities
    # juejin: xxx
    #jianshu: 
    # twitter: 
    mail: serendipity.zsh.spring@gmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: xxxx  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


